// <auto-generated by scripts/Sync-ProductVersion.ps1>
using System.Reflection;

[assembly: AssemblyVersion("3.0.4.0")]
[assembly: AssemblyFileVersion("3.0.4.0")]
[assembly: AssemblyInformationalVersion("3.0.4")]
