// <auto-generated by scripts/Sync-ProductVersion.ps1>
using System.Reflection;

[assembly: AssemblyVersion("2.1.1.0")]
[assembly: AssemblyFileVersion("2.1.1.0")]
[assembly: AssemblyInformationalVersion("2.1.1")]
