// <auto-generated by scripts/Sync-ProductVersion.ps1>
using System.Reflection;

[assembly: AssemblyVersion("2.2.0.0")]
[assembly: AssemblyFileVersion("2.2.0.0")]
[assembly: AssemblyInformationalVersion("2.2.0")]
