import { createProtoStub } from "../protoStub"

export const ClineAsk = {
	FOLLOWUP: "FOLLOWUP",
	PLAN_MODE_RESPOND: "PLAN_MODE_RESPOND",
	ACT_MODE_RESPOND: "ACT_MODE_RESPOND",
	COMMAND: "COMMAND",
	COMMAND_OUTPUT: "COMMAND_OUTPUT",
	COMPLETION_RESULT: "COMPLETION_RESULT",
	TOOL: "TOOL",
	API_REQ_FAILED: "API_REQ_FAILED",
	RESUME_TASK: "RESUME_TASK",
	RESUME_COMPLETED_TASK: "RESUME_COMPLETED_TASK",
	MISTAKE_LIMIT_REACHED: "MISTAKE_LIMIT_REACHED",
	BROWSER_ACTION_LAUNCH: "BROWSER_ACTION_LAUNCH",
	USE_MCP_SERVER: "USE_MCP_SERVER",
	NEW_TASK: "NEW_TASK",
	CONDENSE: "CONDENSE",
	SUMMARIZE_TASK: "SUMMARIZE_TASK",
	REPORT_BUG: "REPORT_BUG",
	USE_SUBAGENTS: "USE_SUBAGENTS",
	UNRECOGNIZED: "UNRECOGNIZED",
} as const
export type ClineAsk = (typeof ClineAsk)[keyof typeof ClineAsk]

export type ClineMessage = any
export const ClineMessage = createProtoStub("ClineMessage")

export const ClineMessageType = {
	ASK: "ASK",
	SAY: "SAY",
	UNRECOGNIZED: "UNRECOGNIZED",
} as const
export type ClineMessageType = (typeof ClineMessageType)[keyof typeof ClineMessageType]

export const ClineSay = {
	TASK: "TASK",
	ERROR: "ERROR",
	ERROR_RETRY: "ERROR_RETRY",
	API_REQ_STARTED: "API_REQ_STARTED",
	API_REQ_FINISHED: "API_REQ_FINISHED",
	TEXT: "TEXT",
	REASONING: "REASONING",
	COMPLETION_RESULT_SAY: "COMPLETION_RESULT_SAY",
	USER_FEEDBACK: "USER_FEEDBACK",
	USER_FEEDBACK_DIFF: "USER_FEEDBACK_DIFF",
	API_REQ_RETRIED: "API_REQ_RETRIED",
	COMMAND_SAY: "COMMAND_SAY",
	COMMAND_OUTPUT_SAY: "COMMAND_OUTPUT_SAY",
	TOOL_SAY: "TOOL_SAY",
	SHELL_INTEGRATION_WARNING: "SHELL_INTEGRATION_WARNING",
	BROWSER_ACTION_LAUNCH_SAY: "BROWSER_ACTION_LAUNCH_SAY",
	BROWSER_ACTION: "BROWSER_ACTION",
	BROWSER_ACTION_RESULT: "BROWSER_ACTION_RESULT",
	MCP_SERVER_REQUEST_STARTED: "MCP_SERVER_REQUEST_STARTED",
	MCP_SERVER_RESPONSE: "MCP_SERVER_RESPONSE",
	MCP_NOTIFICATION: "MCP_NOTIFICATION",
	USE_MCP_SERVER_SAY: "USE_MCP_SERVER_SAY",
	DIFF_ERROR: "DIFF_ERROR",
	DELETED_API_REQS: "DELETED_API_REQS",
	CLINEIGNORE_ERROR: "CLINEIGNORE_ERROR",
	COMMAND_PERMISSION_DENIED: "COMMAND_PERMISSION_DENIED",
	CHECKPOINT_CREATED: "CHECKPOINT_CREATED",
	LOAD_MCP_DOCUMENTATION: "LOAD_MCP_DOCUMENTATION",
	GENERATE_EXPLANATION: "GENERATE_EXPLANATION",
	INFO: "INFO",
	TASK_PROGRESS: "TASK_PROGRESS",
	HOOK_STATUS: "HOOK_STATUS",
	HOOK_OUTPUT_STREAM: "HOOK_OUTPUT_STREAM",
	SUBAGENT_STATUS: "SUBAGENT_STATUS",
	USE_SUBAGENTS_SAY: "USE_SUBAGENTS_SAY",
	SUBAGENT_USAGE: "SUBAGENT_USAGE",
	CONDITIONAL_RULES_APPLIED: "CONDITIONAL_RULES_APPLIED",
	UNRECOGNIZED: "UNRECOGNIZED",
} as const
export type ClineSay = (typeof ClineSay)[keyof typeof ClineSay]
