param([switch]$Check)

$ErrorActionPreference = "Stop"
$repoRoot = Split-Path -Parent $PSScriptRoot
[xml]$versionProps = Get-Content -LiteralPath (Join-Path $repoRoot "packaging\ProductVersion.props")
$version = [string]$versionProps.Project.PropertyGroup.ProductVersion
$assemblyVersion = [string]$versionProps.Project.PropertyGroup.ProductAssemblyVersion
if ($version -notmatch '^\d+\.\d+\.\d+$' -or $assemblyVersion -ne "$version.0") {
    throw "ProductVersion.props must contain a three-part ProductVersion and matching four-part ProductAssemblyVersion."
}

foreach ($relativePath in @("packaging\vs2022-17.0\source.extension.vsixmanifest", "packaging\vs2022-17.12\source.extension.vsixmanifest")) {
    $path = Join-Path $repoRoot $relativePath
    [xml]$manifest = Get-Content -LiteralPath $path
    $actual = [string]$manifest.PackageManifest.Metadata.Identity.Version
    if ($Check) {
        if ($actual -ne $version) { throw "$relativePath has version $actual; expected $version." }
    } elseif ($actual -ne $version) {
        $content = [System.IO.File]::ReadAllText($path)
        $identityPattern = '<Identity\b[^>]*\bVersion="[^"]*"[^>]*/>'
        $identityMatches = [regex]::Matches($content, $identityPattern)
        if ($identityMatches.Count -ne 1) {
            throw "$relativePath must contain exactly one self-closing Identity element with a Version attribute."
        }

        $identity = $identityMatches[0].Value
        $updatedIdentity = [regex]::Replace($identity, '\bVersion="[^"]*"', "Version=`"$version`"", 1)
        $updated = $content.Substring(0, $identityMatches[0].Index) +
            $updatedIdentity +
            $content.Substring($identityMatches[0].Index + $identityMatches[0].Length)
        [System.IO.File]::WriteAllText($path, $updated, [System.Text.UTF8Encoding]::new($false))
    }
}

$generatedPath = Join-Path $repoRoot "src\extension\Properties\ProductVersionAssemblyInfo.cs"
$generated = "// <auto-generated by scripts/Sync-ProductVersion.ps1>`r`nusing System.Reflection;`r`n`r`n[assembly: AssemblyVersion(`"$assemblyVersion`")]`r`n[assembly: AssemblyFileVersion(`"$assemblyVersion`")]`r`n[assembly: AssemblyInformationalVersion(`"$version`")]`r`n"
if ($Check) {
    if (-not (Test-Path -LiteralPath $generatedPath) -or (Get-Content -LiteralPath $generatedPath -Raw) -ne $generated) {
        throw "ProductVersionAssemblyInfo.cs is stale. Run scripts\Sync-ProductVersion.ps1."
    }
} else {
    [System.IO.File]::WriteAllText($generatedPath, $generated, [System.Text.UTF8Encoding]::new($false))
}

Write-Host "Product version synchronized: $version"
